### ISSUE TITLE
Remove `python` app checks from auxiliary apps

### ISSUE THREAD

**Issue by acuarica** [trufflesuite/vscode-ext#137]
Python was declared as an auxiliary app, but it is not needed anymore[1]. It is shown as a required app in the Output channel, but the extension never checks if it is installed. This produces an inconsistent output.

![image](https://user-images.githubusercontent.com/4592980/178493765-181d9066-b31b-47e6-af55-da8d76ddd94c.png)
(log was modified to display executing command and arguments)

By removing this unnecessary check, we display a more consistent output to the user, and at the same time remove unnecessary code.

---

[1] https://github.com/microsoft/vscode-azure-blockchain-ethereum/issues/67#issuecomment-722619465

**Comment by kevinbluer** [comment]
As discussed, yeah all good to go ahead and remove the check. Also thanks for adding the `refactor` label 👌

**Comment by xhulz** [comment]
Hey guys, sorry for the delay.

Maybe we need to re-think about the python validation.

I think Python validation is required app because Windows needs the `npm install --global windows-build-tools` installed before install `npm install -g truffle`. It's not a Truffle problem at all, but maybe the Microsoft guys put the python validation there to avoid problems like that: https://stackoverflow.com/questions/70874761/why-this-truffle-installation-error-coming#:~:text=You%20need%20to%20install%20the%20latest%20version%20of%20node%2C%20npm,node%20%2D%20v16.

Thoughts?

**Comment by acuarica** [comment]
Hi @xhulz, 

According to https://github.com/microsoft/vscode-azure-blockchain-ethereum/issues/67#issuecomment-722619465, it seems Python is not needed anymore. The Python code was not being executed in any case. I believe it's better if we remove it for now to avoid confusion.

**Comment by xhulz** [comment]
Hey @acuarica!

Thank you for letting me know. I was afraid to get problems on Windows as we had in the past :)
