### ISSUE TITLE
Command 'Truffle: Start Ganache' resulted in an error (command 'truffle-vscode.startGanacheServer' not found)

### ISSUE THREAD

**Issue by xhulz** [trufflesuite/vscode-ext#68]
How to reproduce:
 - Open the Visual Studio Code for the first time
 - Go to the "Command Pallete"
 - Choose "Truffle: Start Ganache" or "Truffle: Stop Ganache"

If the extension has previously loaded, the problem does not happen.

![Screenshot 2022-04-21 at 16 53 12](https://user-images.githubusercontent.com/32708942/164501479-3683da6a-3b6d-4735-b139-7e0efc187efd.png)

**Comment by kevinbluer** [comment]
Closing in favor of https://github.com/trufflesuite/vscode-ext/issues/138

**Comment by acuarica** [comment]
Hi @kevinbluer, thanks for taking care of this. Just for reference, I believe that this issue was fixed in

https://github.com/trufflesuite/vscode-ext/commit/8950b3ad19f3a944ad251df2ea2845d7e0c03608#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R57-R58

when both `truffle-vscode.startGanacheServer` and `truffle-vscode.stopGanacheServer` were added to the `activationEvents` list.
